name: 'Deploy Storybook to GitHub Pages'
description: 'Build and deploy storybook code to GitHub pages'
branding:
  icon: upload-cloud
  color: red
inputs:
  checkout:
    description: 'Specifies if this action should checkout the code'
    required: false
    default: 'true'
  path:
    description: 'Specifies the path of the static assets after building'
    required: false
    # TODO: where does storybook output by default?
    default: 'dist/storybook'
  install_command:
    description: 'Specifies the command to run the installation.'
    required: false
    default: 'npm ci'
  build_command:
    description: 'Specifies the command to run after npm ci for the build'
    required: false
    default: 'npm run build-storybook'
outputs:
  page_url:
    description: "The URL of the page"
    value: ${{ steps.deploy.outputs.page_url }}

  

runs:
  using: 'composite'

  steps:
    - name: Checkout if required
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: 'Build'
      shell: bash
      env:
        INSTALL_COMMAND: ${{ inputs.install_command }}
        BUILD_COMMAND: ${{ inputs.build_command }}
      run: |
        echo "::group::Build"
        eval "$INSTALL_COMMAND"
        eval "$BUILD_COMMAND"
        echo "::endgroup::"

    - name: 'upload'
      uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c # v2
      with: 
        path: ${{ inputs.path }}

    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@13b55b33dd8996121833dbc1db458c793a334630 # v3
      with:
        token: ${{ github.token }}
